import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, query, where } from 'firebase/firestore';
import firebaseConfig from './firebase-applet-config.json';

const app = initializeApp(firebaseConfig);
const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);

async function analyzeMeters() {
  console.log('🔍 Analyse des compteurs dans Firestore...\n');

  const metersSnap = await getDocs(collection(db, 'meters'));
  const meters = metersSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

  console.log(`📊 Total des compteurs: ${meters.length}\n`);

  // Par statut
  const statusCount: Record<string, number> = {};
  meters.forEach(m => {
    const status = (m as any).status || 'INCONNU';
    statusCount[status] = (statusCount[status] || 0) + 1;
  });

  console.log('📋 Répartition par statut:');
  Object.entries(statusCount).forEach(([status, count]) => {
    console.log(`  ${status}: ${count}`);
  });

  // Par diamètre
  const diameterCount: Record<string, number> = {};
  meters.forEach(m => {
    const diameter = (m as any).diameterId || 'INCONNU';
    diameterCount[diameter] = (diameterCount[diameter] || 0) + 1;
  });

  console.log('\n📏 Répartition par diamètre:');
  Object.entries(diameterCount).forEach(([diameter, count]) => {
    console.log(`  ${diameter}: ${count}`);
  });

  // Compteurs avec brandId = 'DEFAULT' (créés automatiquement)
  const defaultBrand = meters.filter(m => (m as any).brandId === 'DEFAULT');
  console.log(`\n⚠️  Compteurs avec marque DEFAULT (auto-créés): ${defaultBrand.length}`);

  // Compteurs avec numéros de série automatiques (format: DN15_timestamp_num)
  const autoGenerated = meters.filter(m => {
    const serial = (m as any).serialNumber || '';
    return /^\w+_\d+_\d+$/.test(serial);
  });
  console.log(`⚠️  Compteurs avec numéros auto-générés: ${autoGenerated.length}`);

  // Afficher quelques exemples de compteurs auto-générés
  if (autoGenerated.length > 0) {
    console.log('\n📝 Exemples de compteurs auto-générés:');
    autoGenerated.slice(0, 5).forEach(m => {
      console.log(`  - ${(m as any).serialNumber} (${(m as any).diameterId}, ${(m as any).status})`);
    });
  }

  console.log('\n✅ Analyse terminée');
}

analyzeMeters().catch(console.error);
