import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, writeBatch, doc } from 'firebase/firestore';
import firebaseConfig from './firebase-applet-config.json';
import * as readline from 'readline';

const app = initializeApp(firebaseConfig);
const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function askQuestion(query: string): Promise<string> {
  return new Promise(resolve => rl.question(query, resolve));
}

async function cleanupAutoGeneratedMeters() {
  console.log('🧹 Nettoyage des compteurs auto-générés...\n');

  // Récupérer tous les compteurs
  const metersSnap = await getDocs(collection(db, 'meters'));
  const meters = metersSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

  // Filtrer les compteurs auto-générés (format: DN15_timestamp_num)
  const autoGenerated = meters.filter(m => {
    const serial = (m as any).serialNumber || '';
    return /^\w+_\d+_\d+$/.test(serial);
  });

  console.log(`📊 Compteurs auto-générés trouvés: ${autoGenerated.length}\n`);

  if (autoGenerated.length === 0) {
    console.log('✅ Aucun compteur auto-généré à supprimer.');
    rl.close();
    return;
  }

  // Afficher quelques exemples
  console.log('📝 Exemples de compteurs qui seront supprimés:');
  autoGenerated.slice(0, 5).forEach(m => {
    console.log(`  - ${(m as any).serialNumber}`);
  });
  console.log('  ...\n');

  // Demander confirmation
  const answer = await askQuestion(`⚠️  Voulez-vous vraiment supprimer ces ${autoGenerated.length} compteurs? (oui/non): `);
  
  if (!['oui', 'o', 'yes', 'y'].includes(answer.toLowerCase())) {
    console.log('❌ Opération annulée.');
    rl.close();
    return;
  }

  console.log('\n🗑️  Suppression en cours...');

  // Supprimer par lots de 500 (limite Firestore)
  const batchSize = 500;
  let deleted = 0;

  for (let i = 0; i < autoGenerated.length; i += batchSize) {
    const batch = writeBatch(db);
    const batchMeters = autoGenerated.slice(i, i + batchSize);

    batchMeters.forEach(meter => {
      batch.delete(doc(db, 'meters', meter.id));
    });

    await batch.commit();
    deleted += batchMeters.length;
    console.log(`  ✓ ${deleted}/${autoGenerated.length} supprimés`);
  }

  console.log(`\n✅ ${deleted} compteurs auto-générés supprimés avec succès!`);
  console.log(`📊 Il vous reste maintenant ${meters.length - deleted} compteurs.`);
  
  rl.close();
}

cleanupAutoGeneratedMeters().catch(err => {
  console.error('❌ Erreur:', err);
  rl.close();
});
